---
- name: Ensure Extra RPMs Repo Is Enabled (RHEL7)
  rhsm_repository:
    name: '{{ podman_rhel7_extra_repo }}'
    state: enabled
  when:
    - ansible_os_family | lower == 'redhat'
    - ansible_distribution | lower == 'redhat'
    - ansible_distribution_major_version == '7'

- name: Ensure Podman Is Present
  become: true
  package:
    name: '{{ podman_package }}'
    state: present
